package route

import (
	"bytes"
	"context"
	"errors"
	"github.com/gin-contrib/graceful"
	"github.com/leslieleung/gin-application-template/internal/config"
	"github.com/leslieleung/gin-application-template/internal/middleware"
	healthcheck "github.com/tavsec/gin-healthcheck"
	"github.com/tavsec/gin-healthcheck/checks"
	healthcheckcfg "github.com/tavsec/gin-healthcheck/config"
	"io"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/gin-contrib/requestid"
	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
	_ "github.com/leslieleung/gin-application-template/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/leslieleung/gin-application-template/internal/controller"
	"github.com/leslieleung/gin-application-template/internal/log"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func StartRouter() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	r, err := graceful.Default(
		graceful.WithAddr(":" + strconv.Itoa(config.GetConfig().GetInt("app.port"))),
	)
	if err != nil {
		panic(err)
	}
	defer r.Close()

	registerMiddlewares(r)
	registerHealthCheck(r, ctx)

	r.GET("/ping", controller.PingPong)
	r.Any("/echo", controller.Echo)
	// Swagger API docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	if err := r.RunWithContext(ctx); err != nil && !errors.Is(err, context.Canceled) {
		panic(err)
	}
}

func registerMiddlewares(r *graceful.Graceful) {
	r.Use(requestid.New())
	r.Use(middleware.WithLogger())
	logger := log.Default()
	r.Use(ginzap.GinzapWithConfig(logger, &ginzap.Config{
		TimeFormat: time.RFC3339Nano,
		UTC:        true,
		SkipPaths:  []string{},
		Context: func(c *gin.Context) []zapcore.Field {
			fields := []zapcore.Field{}
			fields = append(fields, zap.String("request_id", requestid.Get(c)))

			// log request body
			var body []byte
			var buf bytes.Buffer
			tee := io.TeeReader(c.Request.Body, &buf)
			body, _ = io.ReadAll(tee)
			c.Request.Body = io.NopCloser(&buf)
			fields = append(fields, zap.String("body", string(body)))
			return fields
		},
	}))
}

func registerHealthCheck(r *graceful.Graceful, ctx context.Context) {
	c := []checks.Check{
		checks.NewContextCheck(ctx, "signals"),
		// more checks here
	}
	err := healthcheck.New(r.Engine, healthcheckcfg.DefaultConfig(), c)
	if err != nil {
		return
	}
}
