package controller

import "github.com/gin-gonic/gin"

// PingPong godoc
// @Summary A gin example
// @Description
// @Tags autogenerated
// @Produce json
// @Router /ping [get]
func PingPong(c *gin.Context) {
	c.JSON(200, gin.H{
		"message": "pong",
	})
}
